# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Gems
gems:
    - jekyll-paginate

# Site settings
title:          Libelli
tagline:        If it were easy, everyone would do it.
baseurl:        "/"
url:            http://bbengfort.github.io
description: >
    The development journal of <a href="https://twitter.com/bbengfort">@bbengfort</a>
    including notes and ramblings from his various programming activities.

author:
    name:       'Benjamin Bengfort'
    url:        https://github.com/bbengfort
    github:     bbengfort
    twitter:    bbengfort

# Build settings
markdown:       redcarpet
highlighter:    pygments

# Custom Variables
paginate:       10
version:        1.0

github:
    repo:       https://github.com/bbengfort/bbengfort.github.io
