name: Publish

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"

      - name: Build Hugo Site
        env:
          HUGO_PARAMS_GOOGLEANALYTICS: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        run: hugo --minify

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages